stages:
  - build-upload
  - purge

variables:
  STORAGE_ZONE: blossomos

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

build-upload-main:
  stage: build-upload
  image: ghcr.io/ublue-os/devcontainer:latest
  tags:
    - bigboi-docker-priv
  script:
    - just build-iso blossomos main main
    - just upload-ftp main

build-upload-nvidia-open:
  stage: build-upload
  image: ghcr.io/ublue-os/devcontainer:latest
  tags:
    - bigboi-docker-priv
  script:
    - just build-iso blossomos main nvidia-open
    - just upload-ftp nvidia-open

purge-cache:
  stage: purge
  image: alpine:latest
  script:
    - apk add --no-cache curl jq
    - |
      PULLZONE_ID=$(curl -fsS --url https://api.bunny.net/pullzone \
        --header "AccessKey: $BUNNY_API_KEY" \
        | jq -r ".[] | select(.Name == \"$STORAGE_ZONE\") | .Id")
      curl -fsS --request POST \
        --url "https://api.bunny.net/pullzone/$PULLZONE_ID/purgeCache" \
        --header "AccessKey: $BUNNY_API_KEY" \
        --header 'Content-Type: application/json'
  needs:
    - build-upload-main
    - build-upload-nvidia-open
