stages:
  - build-upload

variables:
  R2_BUCKET: blossom-cdn
  R2_ENDPOINT: https://7ad15a3d6489a22ad3c2c2fc2ed258db.eu.r2.cloudflarestorage.com

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"

build-upload-main:
  stage: build-upload
  image: ghcr.io/ublue-os/devcontainer:latest
  tags:
    - bigboi-docker-priv
  script:
    - just build-iso blossomos main main
    - just upload-r2 main

build-upload-nvidia-open:
  stage: build-upload
  image: ghcr.io/ublue-os/devcontainer:latest
  tags:
    - bigboi-docker-priv
  script:
    - just build-iso blossomos main nvidia-open
    - just upload-r2 nvidia-open
