---
when:
  - event: push
    branch: main
  - event: cron
    cron: weekly-build
  - event: manual

variables:
  - &ftp_env
    FTP_PASSWORD:
      from_secret: ftp_password
  - &ghcr_env
    GITHUB_TOKEN:
      from_secret: github_token
    GITHUB_USERNAME:
      from_secret: github_username

steps:
  - name: build-iso-main
    image: quay.io/fedora/fedora:44
    pull: true
    privileged: true
    environment:
      <<: *ghcr_env
    commands:
      # Install necessary tools
      - dnf install -y podman just git curl jq
      - echo "$GITHUB_TOKEN" | podman login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      # Force update of target image for security purposes
      - podman rmi -f git.blossomos.org/blossom/image:latest || true
      - podman pull git.blossomos.org/blossom/image:latest
      # Finally, execute build
      - just build-iso blossomos latest main

  - name: upload-iso-main
    image: quay.io/fedora/fedora:44
    environment:
      <<: *ftp_env
    commands:
      - dnf install -y just curl jq
      - just upload-ftp main
    depends_on: [build-iso-main]

  - name: build-iso-nvidia-open
    image: quay.io/fedora/fedora:44
    pull: true
    privileged: true
    environment:
      <<: *ghcr_env
    commands:
      - dnf install -y podman just git curl jq
      - echo "$GITHUB_TOKEN" | podman login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - podman rmi -f git.blossomos.org/blossom/image:latest-nvidia || true
      - podman pull git.blossomos.org/blossom/image:latest-nvidia
      - just build-iso blossomos latest nvidia-open

  - name: upload-iso-nvidia-open
    image: quay.io/fedora/fedora:44
    environment:
      <<: *ftp_env
    commands:
      - dnf install -y just curl jq
      - just upload-ftp nvidia-open
    depends_on: [build-iso-nvidia-open]
